package com.example.demo.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.ToString;

@Data
@ToString
public class Test implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.test.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.test.file
     *
     * @mbg.generated
     */
    private byte[] file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.test
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}