package com.example.demo.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.ToString;

@Data
@ToString
public class Test2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.test2.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.test2.file
     *
     * @mbg.generated
     */
    private Long file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}