package com.example.demo.mapper;

import com.example.demo.entity.Test2;
import com.example.demo.entity.Test2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Test2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    long countByExample(Test2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    int deleteByExample(Test2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    int insert(Test2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    int insertSelective(Test2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    List<Test2> selectByExample(Test2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    Test2 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Test2 record, @Param("example") Test2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Test2 record, @Param("example") Test2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Test2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test2
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Test2 record);
}